[package]
name = "rusty-donut"
version = "0.1.0"
authors = ["Ismael Hajy <ismael.hajy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
